# Generated by Django 4.0.1 on 2024-09-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='user',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.CharField(max_length=25),
        ),
    ]
