# Generated by Django 4.0.1 on 2024-10-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0002_alter_buyer_user_alter_seller_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('transaction_type', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=6)),
                ('date', models.DateField()),
                ('quantity_litres', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='date_of_buying',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='quantity_litres',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='date_of_selling',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='quantity_litres',
        ),
    ]
