# Generated by Django 4.0.1 on 2024-11-01 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0003_transaction_remove_buyer_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='mobile_number',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='mobile_number',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='quantity_litres',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='buyer',
            name='address',
            field=models.CharField(default='Unknown address', max_length=255),
        ),
        migrations.AddField(
            model_name='buyer',
            name='name',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.CharField(default='Unknown address', max_length=255),
        ),
        migrations.AddField(
            model_name='seller',
            name='name',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='milk.buyer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='litres',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='milk.seller'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=10),
        ),
    ]
