# Generated by Django 4.0.1 on 2024-11-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0008_alter_transaction_buyer_alter_transaction_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='liters',
            new_name='litres',
        ),
    ]
